/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.adebard.telephonymanager;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Context;
import android.telephony.TelephonyManager;
import android.app.Activity;

@Kroll.module(name="Telephonymanager", id="com.adebard.telephonymanager")
public class TelephonymanagerModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TelephonymanagerModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TelephonymanagerModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String getPhoneNumber()
	{
		Activity cn = TiApplication.getAppRootOrCurrentActivity();

		TelephonyManager tm = (TelephonyManager) cn.getSystemService(Context.TELEPHONY_SERVICE);
		String phone = tm.getLine1Number();

		return phone;
	}

}

